# Generated by Django 5.0.6 on 2024-07-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auto_token',
            new_name='auth_token',
        ),
    ]
